### ISSUE TITLE
Markdown内容过少时，内容区样式问题

### ISSUE THREAD

**Issue by Nikaple** [KuangPF/dumi-theme-antd#33]
截图如下：
<img width="2023" alt="image" src="https://github.com/KuangPF/dumi-theme-antd/assets/24775744/81907d85-85a4-4db8-bd99-36c8cf9e92d5">

默认主题内容区样式有设置 min-height，所以没有问题

```css
.dumi-default-header+main>.dumi-default-content, .dumi-default-doc-layout-mobile-bar+main>.dumi-default-content {
  min-height: calc(100vh - 76px)
}
```
